import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./Sidebar";
import Search from "./Search";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="block space-y-8 py-12">
          <Search />

          <div className="grid min-h-screen gap-4 grid-cols-4 px-4">
            <div className="col-span-1">
              <Sidebar />
            </div>
            <div className="col-span-3">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
